### ISSUE TITLE
Is it possible to load 3D object dynamically.

### ISSUE THREAD

**Issue by tahmidmozaffar** [TTimo/unity-android-example#2]
Hi, I have run the project and it is running fine. Thank you for this. But is it possible to load a 3D object (obj/mtl or .3ds file) dynamically in this way by loading the model using UnityPlayer from unity3d? it will be a great help if you can give any suggestion. Thanks.

**Comment by apollow** [comment]
I think this is outside the scope of what I got for the project, and I think is best asked in the Unity forums!

**Comment by tahmidmozaffar** [comment]
Ok i will. But let me ask.. in this project when I run the app, there is a box object showing in the UnityPlayer which is in a FrameLayout.. right?  is it possible to load other object dynamically from resource/asset folder? 

Actually I went through the code and could not find any command to create/load the model in the unityplayer. All i found is...

```
mUnityPlayer = new UnityPlayer(this);\n
int glesMode = mUnityPlayer.getSettings().getInt("gles_mode", 1);\n
mUnityPlayer.init(glesMode, false);\n
```

So it is loaded in the Unity3d then exported from there?

**Comment by TTimo** [comment]
I can't help you I'm afraid. I wrote this code as an early experiment into Unity3D for a customer, but we ended up picking a different technology so I never went further with it.

I'm surprised this code still works at all really. There have been several Unity and several Android releases since this. I will probably archive this project and delete it eventually.
